version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - ./app-data:/app/data  # Volumen para persistir la base de datos SQLite
    environment:
      - DB_PATH=/app/data/users.db  # Ruta del archivo SQLite dentro del contenedor
    depends_on:
      - sqlite  # La aplicación depende del servicio SQLite
    networks:
      - app-network

 


networks:
  app-network:
    driver: bridge
