FROM golang:1.23.0

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de la aplicación
COPY . .

# Instalar las dependencias
RUN go mod download


# Build the go app
RUN go build -o main .

# Expose port
EXPOSE 8181

# Define the command to run the app
CMD ["./main"]